"""Venue removed

Revision ID: d9fb7ace53cb
Revises: d33d85db473c
Create Date: 2026-06-22 23:30:58.676588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fb7ace53cb'
down_revision: Union[str, Sequence[str], None] = 'd33d85db473c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hackathons', 'venue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathons', sa.Column('venue', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
